name: Run Tests and Lint

on:
  pull_request: {}

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          ./setup_test_environment.sh

      - name: Run tests
        run: python -m pytest
  run_black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install black
        run: pip install black

      - name: Run black
        run: python -m black --check .
  run_flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: python -m flake8 .
